name: Automated Tests

on: pull_request

jobs:
  bun_api:
    name: Bun API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bun run api:test

  bun_web:
    name: Bun Web and Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: local_user
          POSTGRES_PASSWORD: localpassword
          POSTGRES_DB: local_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bun run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: local_user
          POSTGRES_PASSWORD: localpassword
          POSTGRES_DB: local_db
          DATABASE_URL: postgres://local_user:localpassword@localhost:5432/local_db
